add test file, some changes solidity vs code
cclp-project/cclp-contracts pull request #8
Opened 2019-02-27 03:04 UTC by UncleVultur

Some test on PositiveTests.js file and "" to '' on import contract.

2019-02-27 03:47 UTC, ajunge requested changes
Good work on the tests. No need for changes on the FiatToken.sol file. Since no contract file changed no need to change the `build/*` file

2019-02-27 03:47 UTC, ajunge commented on contracts/FiatToken.sol
> +import "../node_modules/openzeppelin-solidity/contracts/token/ERC20/ERC20.sol";
This is not needed. Is solved using `.vscode/settings.json` on master branch

Idea from: https://medium.com/coinmonks/solidity-import-in-vs-code-the-right-way-82baa1cc5a71

2019-02-27 19:07 UTC, UncleVultur commented
> Good work on the tests. No need for changes on the FiatToken.sol file. Since no contract file changed no need to change the `build/*` file

Sorry, the truffle compiler change the build/* file

2019-02-28 08:54 UTC, ajunge approved these changes
Looks good

2019-02-28 08:58 UTC, merged